name: Build and Check for Changes

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get dependencies
        uses: extractions/setup-just@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Build project
        run: |
          export BASE_URL="/RFCs"
          just build

      - name: Check for changes
        run: |
          git status --porcelain
          if [[ -n $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes after the build."
            exit 1
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' # to avoid deploying on PRs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
