name: Build and Check for Changes

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get just
        uses: extractions/setup-just@v1

      - name: Get pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Build project
        env:
          BASE_URL: "/RFCs"
        run: |
          just setup
          just deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' # to avoid deploying on PRs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
